version: 2
tools:
  treefmt: &treefmt
    format-command: "treefmt --stdin ${INPUT}"
    format-stdin: true

languages:
  go:
    - <<: *treefmt
  nix:
    - <<: *treefmt
  python:
    - <<: *treefmt
