shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
hooks.post = """
zcompile() zsh-defer builtin zcompile "$@"

# setup rtx with bootstrap
# activate can be deferred but should ensure deno is available for zeno.zsh
function my-rtx-activate() {
  command -v direnv >/dev/null && eval "$( direnv hook zsh )"
  eval "$( rtx activate zsh )" && eval "$( rtx hook-env -s zsh )"
}
RTX_INSTALL_ONLY=1 . "${HOME}/.local/lastresort/bin/rtx" && zsh-defer my-rtx-activate
"""

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]
hooks.pre = "ZSH_AUTOSUGGEST_USE_ASYNC=1; ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=244'"

[plugins.zsh-async]
github = "mafredri/zsh-async"
apply = ["defer"]

[plugins.zsh-256color]
github = "chrissicool/zsh-256color"
apply = ["defer"]

[plugins.git-prompt]
github = "woefe/git-prompt.zsh"
apply = ["defer"]
hooks.post = """
function git-prompt-my-post() {
  ZSH_THEME_GIT_PROMPT_PREFIX=" "
  ZSH_THEME_GIT_PROMPT_SUFFIX=""
  ZSH_THEME_GIT_PROMPT_UNTRACKED=".."
  ZSH_THEME_GIT_PROMPT_UNMERGED="%{$fg[red]%}x"
  ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[green]%}o"
  ZSH_THEME_GIT_PROMPT_UNSTAGED="%{$fg[red]%}+"
}
zsh-defer git-prompt-my-post
"""

[plugins.kube-ps1]
github = "jonmosco/kube-ps1"
apply = ["defer"]

[plugins.cd-gitroot]
apply = ["defer"]
github = "mollifier/cd-gitroot"
hooks.post = "alias gd=cd-gitroot"

[plugins.fzf]
github = "junegunn/fzf"

[plugins.zeno]
github = "yuki-yano/zeno.zsh"
apply = ["defer"]
hooks.pre = "export ZENO_ENABLE_SOCK=1"
hooks.post = """
function zeno-my-post() {
  bindkey ' '  zeno-auto-snippet
  bindkey '^m' zeno-auto-snippet-and-accept-line
  bindkey '^i' zeno-completion
  bindkey '^r' zeno-history-selection
  bindkey '^x^s' zeno-insert-snippet
  bindkey '^x^f' zeno-ghq-cd
  ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(zeno-auto-snippet-and-accept-line)
}
zsh-defer zeno-my-post
"""

[plugins.zsh-nvrepl]
github = "atusy/zsh-nvrepl"
apply = ["defer"]
hooks.post = """
if [[ -n $NVIM ]]; then
  function nvrepl-my-post() {
    NVREPL_FALLBACK_ACCEPT_LINE="zeno-auto-snippet-and-accept-line"
    bindkey '^m' nvrepl-or-accept-line
    ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(nvrepl-or-accept-line)
  }
  zsh-defer nvrepl-my-post
fi
"""

[plugins.ghf]
github = "atusy/gh-fzf"
apply = ["defer"]
hooks.post = "alias gh=ghf"
