#!/usr/bin/env zsh
function source {
  ensure_zcompiled "$@"
  builtin source "$@"
}

function ensure_zcompiled {
  local compiled="$1.zwc"
  if [[ ! -r "$compiled" || "$1" -nt "$compiled" ]]; then
    echo "\033[1;36mCompiling\033[m $1"
    zcompile "$1"
  fi
}

if ! command -v sheldon >/dev/null; then
  curl --proto '=https' -fLsS https://rossmacarthur.github.io/install/crate.sh \
    | bash -s -- --repo rossmacarthur/sheldon --to ~/.local/bin
fi
eval "$(sheldon source)"
zsh-defer unset -f source

# PROMPT
ZSH_THEME_GIT_PROMPT_PREFIX=" "
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_UNTRACKED=".."
ZSH_THEME_GIT_PROMPT_UNMERGED="%{$fg[red]%}x"
ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[green]%}o"
ZSH_THEME_GIT_PROMPT_UNSTAGED="%{$fg[red]%}+"
PROMPT_ACCENT_COLOR="$( test -n "$SSH_CLIENT" && echo cyan || echo 112 )"
PROMPT='%F{${PROMPT_ACCENT_COLOR}}[ %3~ ]%F{white}$(gitprompt) $( test -n "${KUBE_PS1_CONTEXT%%N/A}" && kube_ps1 )
%F{${PROMPT_ACCENT_COLOR}}» '

bindkey -e
bindkey "^[[3~" delete-char # Del is delete-char, not tilde

# History
HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000
setopt \
  hist_ignore_all_dups \
  hist_ignore_space \
  hist_no_store \
  hist_reduce_blanks \
  hist_save_no_dups \
  hist_verify \
  share_history \
  inc_append_history

# cd
setopt autocd auto_pushd pushd_ignore_dups

# else
setopt \
  extended_glob \
  mark_dirs \
  interactive_comments \
  noautoremoveslash \
  nomatch \
  notify \
  no_beep \
  no_flow_control \
  no_list_beep \
  numeric_glob_sort \
  print_eight_bit \
  prompt_subst

# completion
LISTMAX=1000
setopt \
  always_last_prompt \
  auto_list \
  auto_menu \
  auto_param_keys \
  auto_param_slash \
  complete_aliases \
  complete_in_word \
  list_types \
  magic_equal_subst \
  menu_complete

## zstyle
### Basic Configuration
zstyle ':completion:*' verbose yes
zstyle ':completion:*' menu select interactive
zstyle ':completion:*' group-name ''
zstyle ':completion:*' completer _expand _complete _match _prefix _approximate _list
zstyle ':completion:*' matcher-list  'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' auto-description 'Specify: %d'
zstyle ':completion:*' select-prompt %SScrolling Active: Current selection at %p%s
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*:options'         description 'yes'
zstyle ':completion:*:*:-subscript-:*' tag-order indexes parameters

### Highlight
# zstyle ':completion:*'              list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*'              list-colors "di=01;34:ln=01;35:so=01;32:ex=01;31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30"
zstyle ':completion:*:messages'     format "$YELLOW" '%d' "$DEFAULT"
zstyle ':completion:*:warnings'     format "$RED" 'No matches for:' "$YELLOW" '%d' "$DEFAULT"
zstyle ':completion:*:descriptions' format "$YELLOW" 'Completing %B%d%b' "$DEFAULT"
zstyle ':completion:*:corrections'  format "$YELLOW" '%B%d% ' "$RED" '(Errors: %e)%b' "$DEFAULT"

### Separator
zstyle ':completion:*'         list-separator ' ==> '
zstyle ':completion:*:manuals' separate-sections true

### Cache
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$HOME/.zsh/cache"

### Others
zstyle ':completion:*' remote-access false
zstyle ':completion:*:sudo:*' command-path $path
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion::complete:*' use-cache true

# Edit command line with favorite editor
autoload -Uz edit-command-line
function edit-command-line2() {
  EDITOR="${EDITOR_CMD:-$EDITOR}" edit-command-line
}
zle -N edit-command-line2
bindkey "^x^e" edit-command-line2

# Set title of the session according to the working directory
autoload -Uz add-zsh-hook
function update_session_title() {
  # .../github.com/atusy/dotfiles -> dotfiles
  # .../github.com/atusy/dotfiles/dot_config/nvim -> dotfiles/.../nvim
  # .../dotfiles/.worktree/branch -> dotfiles@branch
  # .../dotfiles/.worktree/branch/dot_config/nvim -> dotfiles@branch/.../nvim
  export SESSION_TITLE="${1:-${SESSION_TITLE:-}}"
  echo -en "\e]2;${SESSION_TITLE:-$( pwd | sed -E -e 's#.*/\.github\.com/##' -e "s#.*/([^/]+)/\.worktree/#\1@#" -e "s#/.*/#/.../#" -e "s#^/\.\.\./##" )}\a"
}
zsh-defer update_session_title
zsh-defer add-zsh-hook chpwd update_session_title

# Aliases and some useful functions
alias sudo='sudo '
if command -v zoxide > /dev/null; then
  function my-zoxide-init() {
    if [[ "$(command -v zi)" =~ "^alias .+" ]]; then
      unalias zi
    fi
    eval "$(zoxide init zsh)"
  }
  zsh-defer my-zoxide-init
fi
if command -v htop > /dev/null; then
  alias top='htop'
fi
if command -v duf > /dev/null; then
  alias df='duf'
else
  alias df='df -h'
fi
if command -v procs > /dev/null; then
  alias ps='procs'
fi
if command -v gdu > /dev/null; then
  alias du='gdu'
fi
if command -v eza > /dev/null; then
  alias ls='eza -l --time-style=iso'
fi
if command -v bat > /dev/null; then
  alias cat='bat'
fi
if command -v gojq > /dev/null; then
  alias jq='gojq'
  alias yq='gojq --yaml-input'
fi
if command -v wget2 > /dev/null
then
  alias wget='wget2 -c' # resumable
elif command -v wget > /dev/null; then
  alias wget='wget -c' # resumable
fi
if command -v nvim > /dev/null; then
  alias vim='nvim'
  if [[ -n $NVIM_LISTEN_ADDRESS ]] && command -v nvr > /dev/null; then
    function man() {
      if [[ $# -eq 1 ]]; then
        nvr -cc "Man $1" 2>/dev/null || command man "$1"
      else
        command man "$@"
      fi
    }
  fi
fi
if command -v xdg-open > /dev/null; then
  function open() {
    xdg-open "$@" 2>/dev/null
  }
fi

if command -v kubectl > /dev/null; then
  function kubeconfig() {
    local RES
    local CODE
    local LIST
    LIST="$(
      find "${1:-${HOME}/.kube}" -mindepth 1 -maxdepth 1 -type f | grep -v '/kubectx$' # exclude kubectx
      echo "/dev/null" # to disable kubectl
    )"
    RES="$( echo "$LIST" | fzf --preview 'cat {}' )"
    CODE="$?"
    if [[ $CODE -ne 0 ]]; then
      return $CODE
    fi
    export KUBECONFIG="$RES"
  }
  alias kunset='command kubectl config unset current-context'
fi

function rename_wezterm_title() {
  local PWD="$( pwd )"
  local GIT_DIR="$( git rev-parse --git-common-dir )"
  if [[ -z "$GIT_DIR" ]]; then
    local TITLE="$( basename "$PWD" )"
  else
    local BASE="$( cd "${GIT_DIR}/../.." && pwd )"
    local TITLE="$( realpath --relative-to="$BASE" "$PWD" )"
  fi
  echo "\x1b]1337;SetUserVar=panetitle=$(echo "$TITLE" | base64)\x07"
}

# local configurations
[[ -f "$HOME/.config/zsh/local.zshrc" ]] && . "$HOME/.config/zsh/local.zshrc"

# .zshrc
if [[ ! -f ~/.zshrc.zwc ]] || [[ ~/.zshrc -nt ~/.zshrc.zwc ]]; then
  zcompile ~/.zshrc
fi
