[formatter.goimports]
command = "goimports"
includes = ["*.go"]
priority = 0

[formatter.gofmt]
command = "gofmt"
includes = ["*.go"]
priority = 1

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.ruff-check]
command = "ruff"
options = ["check", "--fix-only"]
includes = ["*.py"]
priority = 0

[formatter.ruff-format]
command = "ruff"
options = ["format"]
includes = ["*.py"]
priority = 1

[formatter.stylua]
command = "stylua"
includes = ["*.lua"]
