#!/bin/sh

set -eu

DARWIN_USER="${DARWIN_USER:-$(whoami)}"
export DARWIN_USER

DARWIN_HOST="${DARWIN_HOST:-$(hostname -s)}"
export DARWIN_HOST

sudo -E darwin-rebuild switch --flake ~/.config/nix-flake --impure --cores 0
