#!/usr/bin/env -S deno run --allow-read --allow-write --allow-env --allow-run

import * as k from "https://deno.land/x/karabinerts@1.36.0/deno.ts";

const metaKeys: k.FromAndToKeyCode[] = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "0",
  "period",
  "comma",
  "slash",
  "semicolon",
  "quote",
  "hyphen",
  "equal_sign",
  "open_bracket",
  "close_bracket",
  "backslash",
  "grave_accent_and_tilde",
];

k.writeToProfile("Default profile", [
  k.rule("Change CapsLock to Ctrl")
    .manipulators([
      k.map({ key_code: "caps_lock" })
        .to({ key_code: "left_control" })
        .toIfAlone({ key_code: "escape" })
        .parameters({ "basic.to_if_alone_timeout_milliseconds": 50 }),
    ]),

  k.rule(
    "felis: Option as Meta (ESC prefix)",
    k.ifApp("^com\\.natsukium\\.felis$"),
  )
    .manipulators(
      metaKeys.map((key) =>
        k.map(key, "⌥")
          .to("escape")
          .to(key)
      ),
    ),
]);

// reload config
const restart = new Deno.Command("karabiner_cli", { args: ["restart"] });
await restart.output();
