font_family      family="UDEV Gothic NF"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 15.0
tab_bar_edge top
tab_bar_style slant

# map
clear_all_shortcuts yes
enabled_layouts splits:split_axis=horizontal
map alt+shift+r load_config_file

# map: tab
map alt+c new_tab
map alt+t next_tab
map alt+T previous_tab


# map: window
map alt+w>alt+v launch --location vsplit
map alt+w>alt+s launch --location hsplit
map alt+w>c close_window
map alt+w>h neighboring_window left
map alt+w>j neighboring_window down
map alt+w>k neighboring_window up
map alt+w>l neighboring_window right
