#!/bin/env bash
if [[ $SKIP_POST_COMMIT -eq 1 ]]
then
  exit 0
fi
set -euo pipefail

readonly HOOKNAME="$( basename "$0" )"
readonly HOOKDIR="$( cd "$( dirname "$0" )" && pwd )"


# Run global hooks
command find "${HOOKDIR}/${HOOKNAME}-files" -type f -name '*.bash' | while read -r fname
do
  if [[ -x "${fname}" ]]
  then
    echo "${HOOKNAME}: $fname" 1>&2
    SKIP_POST_COMMIT=1 "${fname}" "$@"
  fi
done


# Run local hooks
readonly GIT_DIR="$( git rev-parse --git-common-dir )"
readonly LOCAL_HOOK="${GIT_DIR}/.git/hooks/${HOOKNAME}"
if [[ -x "${LOCAL_HOOK}" ]]
then
  echo "${HOOKNAME}: ${LOCAL_HOOK}" 1>&2
  SKIP_POST_COMMIT=1 "${LOCAL_HOOK}" "$@"
fi

