#!/bin/env bash
readonly HOOKNAME="$( basename "$0" )"
readonly HOOKDIR="$( cd "$( dirname "$0" )" && pwd )"

SKIP_HOOK="$(
  eval "echo \"\${SKIP_HOOK_${HOOKNAME^^}:-0}\""
)"

if [[ $SKIP_HOOK -eq 0 ]]
then
  exit 0
fi

# Run global hooks
if [[ -d "${HOOKDIR}/${HOOKNAME}-files" ]]
then
  command find "${HOOKDIR}/${HOOKNAME}-files" -type f -name '*.bash' | while read -r fname
  do
    if [[ -x "${fname}" ]]
    then
      echo "${HOOKNAME}: $fname" 1>&2
      SKIP_HOOK=1 "${fname}" "$@"
    fi
  done
fi


# Run local hooks
readonly GIT_DIR="$( git rev-parse --git-common-dir )"
readonly LOCAL_HOOK="${GIT_DIR}/.git/hooks/${HOOKNAME}"
if [[ -x "${LOCAL_HOOK}" ]]
then
  echo "${HOOKNAME}: ${LOCAL_HOOK}" 1>&2
  SKIP_HOOK=1 "${LOCAL_HOOK}" "$@"
fi

