(atx_h1_marker) @atx_h1_marker
(atx_h2_marker) @atx_h2_marker
(atx_h3_marker) @atx_h3_marker
(atx_h4_marker) @atx_h4_marker
(atx_h5_marker) @atx_h5_marker
(atx_h6_marker) @atx_h6_marker
(atx_heading) @atx_heading
(backslash_escape) @backslash_escape
(block_quote) @block_quote
(block_quote_marker) @block_quote_marker
(code_fence_content) @code_fence_content
(code_span) @code_span
(code_span_delimiter) @code_span_delimiter
(collapsed_reference_link) @collapsed_reference_link
(document) @document
(email_autolink) @email_autolink
(emphasis) @emphasis
(emphasis_delimiter) @emphasis_delimiter
(entity_reference) @entity_reference
(fenced_code_block) @fenced_code_block
(fenced_code_block_delimiter) @fenced_code_block_delimiter
(full_reference_link) @full_reference_link
(hard_line_break) @hard_line_break
(heading_content) @heading_content
(html_block) @html_block
(html_tag) @html_tag
(image) @image
(image_description) @image_description
(indented_code_block) @indented_code_block
(info_string) @info_string
(inline_link) @inline_link
(language) @language
(link_destination) @link_destination
(link_label) @link_label
(link_reference_definition) @link_reference_definition
(link_text) @link_text
(link_title) @link_title
(list) @list
(list_item) @list_item
(list_marker_dot) @list_marker_dot
(list_marker_minus) @list_marker_minus
(list_marker_parenthesis) @list_marker_parenthesis
(list_marker_plus) @list_marker_plus
(list_marker_star) @list_marker_star
(numeric_character_reference) @numeric_character_reference
(paragraph) @paragraph
(setext_h1_underline) @setext_h1_underline
(setext_h2_underline) @setext_h2_underline
(setext_heading) @setext_heading
(shortcut_link) @shortcut_link
(strong_emphasis) @strong_emphasis
(thematic_break) @thematic_break
(uri_autolink) @uri_autolink
