[tools]
neovim = "nightly"
usage = "latest"

# might be useful, but latest can be installed from pacman
# awscli = "latest"
# azure-cli = "latest"
# bat = "latest"
# direnv = "latest"
# fd = "latest"
# fzf = "latest"
# github-cli = "latest"
# go = "latest"
# poetry = "latest"
# ripgrep = "latest"
# rust = "latest"
# terraform = "latest"
