[tools]
rust = "latest"
deno = "latest"
neovim = "nightly"
fzf = "latest"
poetry = "latest"
node = "latest"
python = "latest"
terraform = "latest"
azure-cli = "latest"
bat = "latest"
go = "latest"
ripgrep = "latest"
direnv = "latest"
fd = "latest"
github-cli = "latest"
awscli = "latest"
