[tools]
deno = "latest"
neovim = "nightly"
node = "latest"
python = "latest"
bun = "latest"
azure-cli = "latest"
yarn = "latest"

# might be useful, but latest can be installed from pacman
# awscli = "latest"
# azure-cli = "latest"
# bat = "latest"
# direnv = "latest"
# fd = "latest"
# fzf = "latest"
# github-cli = "latest"
# go = "latest"
# poetry = "latest"
# ripgrep = "latest"
# rust = "latest"
# terraform = "latest"

[settings]
experimental = true
